# 2. Создайте собственный класс-исключение, обрабатывающую ситуацию деления на нуль.
# Проверьте его работу на данных, вводимых пользователем.
# При вводе нуля в качестве делителя программа
# должна корректно обработать эту ситуацию и не завершиться с ошибкой.

класс  ZeroDivisionException ( Исключение ):
    def  __init__ ( self , error_text ):
        я . error_text  =  error_text

    def  __str__ ( сам ):
        вернуть  себя . error_text


попробуйте :
    divisible  =  float ( input ( "Введите первое число >>>" ))   # делимое
    divider  =  float ( input ( "Введите второе число >>>" ))   # делитель
    всего  =  делимый  /  разделитель
    печать ( е "Результат деления: { делится } / { делитель } = { круглая ( всего , 2 ) } " )

    если  итог  ==  0 :
        поднять  ZeroDivisionException ( "0" )

кроме  ZeroDivisionException  как  ноль :
    print ( f "Деление на { zero . error_text } !" )
кроме  ZeroDivisionError :
    print ( f "Деление на ноль!" )
кроме  ValueError :
    print ( "Ошибка! Введите только число!" )
